CREATE TABLE bridgedeals(
    id INTEGER PRIMARY KEY,
    event TEXT,
    site TEXT,
    date TEXT,
    board INTEGER,
    stage TEXT,
    dealer TEXT,
    deal TEXT,
    vulnerable TEXT,
    bidstart TEXT,
    auction TEXT,
    contract TEXT,
    lead TEXT,
    play TEXT,
    declarer TEXT,
    result INTEGER,
    note TEXT,
    westname TEXT,
    eastname TEXT,
    northname TEXT,
    southname TEXT, 
    westpoints INTEGER,
    northpoints INTEGER,
    eastpoints INTEGER,
    southpoints INTEGER,
    scoring TEXT,
    homeTeam TEXT,
    visitteam TEXT,
    room TEXT,
    description TEXT
);